version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - internal
      - shared-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: planner
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c listen_addresses='*'
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
  shared-network:
    external: true