"""CreateModel

Revision ID: 14a808eb8bd0
Revises: 
Create Date: 2026-04-09 18:17:07.741928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a808eb8bd0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('sid')
    )
    op.create_index(op.f('ix_college_name'), 'college', ['name'], unique=False)
    op.create_table('address',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('college_sid', sa.UUID(), nullable=True),
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['college_sid'], ['college.sid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('sid')
    )
    op.create_index(op.f('ix_address_name'), 'address', ['name'], unique=False)
    op.create_table('group',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('address_sid', sa.UUID(), nullable=True),
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_sid'], ['address.sid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('sid')
    )
    op.create_index(op.f('ix_group_is_active'), 'group', ['is_active'], unique=False)
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=False)
    op.create_table('user',
    sa.Column('group_sid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_sid'], ['group.sid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('sid')
    )
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_index(op.f('ix_group_is_active'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_address_name'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_college_name'), table_name='college')
    op.drop_table('college')
    # ### end Alembic commands ###
